# Generated by Django 6.0.3 on 2026-03-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
