# Generated by Django 6.0.3 on 2026-03-06 18:40

import titles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[titles.models.validate_year], verbose_name='Год выпуска'),
        ),
    ]
