# Generated by Django 6.0.3 on 2026-03-06 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_comment_options_alter_review_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='check_score_value',
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Поставьте оценку от 1 до 10.'), django.core.validators.MaxValueValidator(10, message='Поставьте оценку от 1 до 10.')], verbose_name='Оценка'),
        ),
    ]
